/** Country list for the setup form. Codes are ISO 3166-1 alpha-2 so the
 *  geolocation lookup can match them. Ukraine first, then alphabetical. */
export const COUNTRIES: { code: string; uk: string; en: string }[] = [
  { code: "UA", uk: "Україна", en: "Ukraine" },
  { code: "AT", uk: "Австрія", en: "Austria" },
  { code: "AZ", uk: "Азербайджан", en: "Azerbaijan" },
  { code: "BE", uk: "Бельгія", en: "Belgium" },
  { code: "BG", uk: "Болгарія", en: "Bulgaria" },
  { code: "GB", uk: "Велика Британія", en: "United Kingdom" },
  { code: "AM", uk: "Вірменія", en: "Armenia" },
  { code: "GR", uk: "Греція", en: "Greece" },
  { code: "GE", uk: "Грузія", en: "Georgia" },
  { code: "DK", uk: "Данія", en: "Denmark" },
  { code: "EE", uk: "Естонія", en: "Estonia" },
  { code: "IE", uk: "Ірландія", en: "Ireland" },
  { code: "ES", uk: "Іспанія", en: "Spain" },
  { code: "IT", uk: "Італія", en: "Italy" },
  { code: "KZ", uk: "Казахстан", en: "Kazakhstan" },
  { code: "CA", uk: "Канада", en: "Canada" },
  { code: "CY", uk: "Кіпр", en: "Cyprus" },
  { code: "LV", uk: "Латвія", en: "Latvia" },
  { code: "LT", uk: "Литва", en: "Lithuania" },
  { code: "NL", uk: "Нідерланди", en: "Netherlands" },
  { code: "DE", uk: "Німеччина", en: "Germany" },
  { code: "NO", uk: "Норвегія", en: "Norway" },
  { code: "AE", uk: "ОАЕ", en: "United Arab Emirates" },
  { code: "PL", uk: "Польща", en: "Poland" },
  { code: "PT", uk: "Португалія", en: "Portugal" },
  { code: "RO", uk: "Румунія", en: "Romania" },
  { code: "SK", uk: "Словаччина", en: "Slovakia" },
  { code: "SI", uk: "Словенія", en: "Slovenia" },
  { code: "US", uk: "США", en: "United States" },
  { code: "HU", uk: "Угорщина", en: "Hungary" },
  { code: "FI", uk: "Фінляндія", en: "Finland" },
  { code: "FR", uk: "Франція", en: "France" },
  { code: "HR", uk: "Хорватія", en: "Croatia" },
  { code: "CZ", uk: "Чехія", en: "Czechia" },
  { code: "ME", uk: "Чорногорія", en: "Montenegro" },
  { code: "CH", uk: "Швейцарія", en: "Switzerland" },
  { code: "SE", uk: "Швеція", en: "Sweden" },
];

export const countryName = (code: string | null, locale: "uk" | "en") =>
  code ? COUNTRIES.find((country) => country.code === code)?.[locale] ?? code : null;
