"use client";

import { useMemo, useState, type FormEvent } from "react";
import { OriginBadge } from "@/components/origin-badge";
import type { AudioComponent, ComponentOrigin } from "@/lib/types";

type DraftSetup = { title: string; location: string; description: string; isPublished: boolean };

export function SetupBuilder({ initialComponents, isSupabaseReady }: { initialComponents: AudioComponent[]; isSupabaseReady: boolean }) {
  const [catalogue, setCatalogue] = useState(initialComponents);
  const [selected, setSelected] = useState<AudioComponent[]>([]);
  const [query, setQuery] = useState("");
  const [showOwn, setShowOwn] = useState(false);
  const [origin, setOrigin] = useState<ComponentOrigin>("handmade");
  const [setup, setSetup] = useState<DraftSetup>({ title: "", location: "", description: "", isPublished: false });
  const [own, setOwn] = useState({ brand: "", model: "", category: "Підсилювач" });
  const [message, setMessage] = useState<{ type: "error" | "success"; text: string } | null>(null);
  const [saving, setSaving] = useState(false);
  const results = useMemo(() => catalogue.filter((item) => `${item.brand} ${item.model} ${item.category}`.toLocaleLowerCase().includes(query.toLocaleLowerCase())).slice(0, 6), [catalogue, query]);

  function addComponent(component: AudioComponent) { if (!selected.some((item) => item.id === component.id)) setSelected((items) => [...items, component]); setQuery(""); }
  function addOwnComponent() { if (!own.brand.trim() || !own.model.trim()) return; const component: AudioComponent = { id: `new-${crypto.randomUUID()}`, brand: own.brand.trim(), model: own.model.trim(), category: own.category, origin }; setCatalogue((items) => [component, ...items]); addComponent(component); setOwn({ brand: "", model: "", category: "Підсилювач" }); setShowOwn(false); }
  async function saveSetup(event: FormEvent<HTMLFormElement>) { event.preventDefault(); setMessage(null); if (!setup.title.trim() || selected.length === 0) { setMessage({ type: "error", text: "Додайте назву сетапу й хоча б один компонент." }); return; } if (!isSupabaseReady) { setMessage({ type: "error", text: "Додайте ключі Supabase у .env.local, щоб зберігати сетапи." }); return; } setSaving(true); const response = await fetch("/api/setups", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ ...setup, components: selected }) }); const payload = await response.json(); setSaving(false); setMessage(response.ok ? { type: "success", text: setup.isPublished ? "Сетап опубліковано у стрічці." : "Сетап збережено як чернетку." } : { type: "error", text: payload.error ?? "Не вдалося зберегти сетап." }); }

  return <form className="builder-shell" onSubmit={saveSetup}>
    <div className="builder-card">
      <section className="form-section"><h2>1. Про сетап</h2><div className="field"><label htmlFor="setup-title">Назва</label><input id="setup-title" required placeholder="Напр. Музика після дощу" value={setup.title} onChange={(event) => setSetup({ ...setup, title: event.target.value })} /></div><div className="two-fields"><div className="field"><label htmlFor="setup-location">Місто</label><input id="setup-location" placeholder="Львів" value={setup.location} onChange={(event) => setSetup({ ...setup, location: event.target.value })} /></div><div className="field"><label htmlFor="setup-visibility">Видимість</label><select id="setup-visibility" value={setup.isPublished ? "published" : "draft"} onChange={(event) => setSetup({ ...setup, isPublished: event.target.value === "published" })}><option value="draft">Чернетка</option><option value="published">Опублікувати</option></select></div></div><div className="field"><label htmlFor="setup-description">Коротка історія</label><textarea id="setup-description" placeholder="Що це за система і чому вона ваша?" value={setup.description} onChange={(event) => setSetup({ ...setup, description: event.target.value })} /></div></section>
      <section className="form-section"><h2>2. Компоненти</h2><div className="component-search"><label className="field"><span>Знайти в каталозі</span><input className="search-input" value={query} onChange={(event) => { setQuery(event.target.value); setShowOwn(false); }} placeholder="Почніть вводити: KEF, Audio-Technica…" /></label>{query && <div className="search-results">{results.length ? results.map((item) => <button className="search-result" key={item.id} type="button" onClick={() => addComponent(item)}><span className="component-thumb" /><span><b>{item.brand} {item.model}</b><small>{item.category}</small></span><OriginBadge origin={item.origin} /></button>) : <div className="search-empty">У каталозі поки немає збігу. Додайте власний компонент нижче.</div>}</div>}</div><button className="text-link" type="button" onClick={() => setShowOwn((value) => !value)}>{showOwn ? "Сховати форму" : "＋ Додати власний / під замовлення"}</button>
      {showOwn && <div className="form-section"><p className="eyebrow">Новий компонент</p><div className="two-fields"><div className="field"><label htmlFor="own-brand">Бренд або майстер</label><input id="own-brand" value={own.brand} onChange={(event) => setOwn({ ...own, brand: event.target.value })} placeholder="Oleh Audio" /></div><div className="field"><label htmlFor="own-model">Назва моделі</label><input id="own-model" value={own.model} onChange={(event) => setOwn({ ...own, model: event.target.value })} placeholder="Ламповий SE" /></div></div><div className="field"><label htmlFor="own-category">Категорія</label><select id="own-category" value={own.category} onChange={(event) => setOwn({ ...own, category: event.target.value })}><option>Підсилювач</option><option>Акустика</option><option>Програвач</option><option>Стример</option><option>ЦАП</option><option>Аксесуар</option></select></div><div className="field"><label>Походження</label><div className="type-options">{(["standard", "handmade", "custom_order"] as ComponentOrigin[]).map((type) => <button key={type} className={`type-option ${origin === type ? "active" : ""}`} type="button" onClick={() => setOrigin(type)}>{type === "standard" ? "Standard" : type === "handmade" ? "Handmade" : "Custom order"}</button>)}</div></div><button className="button button-outline button-small" type="button" onClick={addOwnComponent}>Додати до сетапу</button></div>}
      {selected.length > 0 && <div className="draft-components">{selected.map((item) => <div className="draft-component" key={item.id}><span className="component-thumb" /><div><b>{item.brand} {item.model}</b><small>{item.category}</small></div><OriginBadge origin={item.origin} /><button className="remove" type="button" aria-label={`Прибрати ${item.model}`} onClick={() => setSelected((items) => items.filter((component) => component.id !== item.id))}>×</button></div>)}</div>}</section>
      {message && <p className={message.type === "error" ? "form-error" : "form-success"}>{message.text}</p>}<button className="button button-dark" type="submit" disabled={saving}>{saving ? "Зберігаємо…" : "Зберегти сетап"} <span>→</span></button>
    </div>
    <aside className="preview-card"><h3>Попередній перегляд</h3><div className="preview-art" /><h2>{setup.title || "Назва вашого сетапу"}</h2><p className="byline">{setup.location || "Ваше місто"} · {setup.isPublished ? "публічно" : "чернетка"}</p><div className="preview-stat"><span>Компоненти</span><span>{selected.length}</span></div><div className="preview-stat"><span>Особливі</span><span>{selected.filter((item) => item.origin !== "standard").length}</span></div></aside>
  </form>;
}
