insert into public.components (brand, model, category, origin) values
  ('Marantz', 'PM7000N', 'Підсилювач', 'standard'),
  ('Marantz', 'PM8006', 'Підсилювач', 'standard'),
  ('Marantz', 'PM6007', 'Підсилювач', 'standard'),
  ('Marantz', 'Model 40n', 'Підсилювач', 'standard'),
  ('Yamaha', 'A-S701', 'Підсилювач', 'standard'),
  ('Yamaha', 'A-S1200', 'Підсилювач', 'standard'),
  ('Denon', 'PMA-600NE', 'Підсилювач', 'standard'),
  ('Denon', 'PMA-1700NE', 'Підсилювач', 'standard'),
  ('NAD', 'C 316BEE V2', 'Підсилювач', 'standard'),
  ('NAD', 'C 328', 'Підсилювач', 'standard'),
  ('Cambridge Audio', 'CXA81', 'Підсилювач', 'standard'),
  ('Cambridge Audio', 'AXA35', 'Підсилювач', 'standard'),
  ('Rotel', 'A11 Tribute', 'Підсилювач', 'standard'),
  ('Rega', 'io', 'Підсилювач', 'standard'),
  ('Rega', 'Brio', 'Підсилювач', 'standard'),
  ('Hegel', 'H120', 'Підсилювач', 'standard'),
  ('Naim', 'Nait XS 3', 'Підсилювач', 'standard'),
  ('Musical Fidelity', 'M3si', 'Підсилювач', 'standard'),
  ('McIntosh', 'MA5300', 'Підсилювач', 'standard'),
  ('KEF', 'LS50 Meta', 'Акустика', 'standard'),
  ('KEF', 'Q150', 'Акустика', 'standard'),
  ('KEF', 'R3 Meta', 'Акустика', 'standard'),
  ('Bowers & Wilkins', '606 S2', 'Акустика', 'standard'),
  ('Bowers & Wilkins', '705 Signature', 'Акустика', 'standard'),
  ('Dali', 'Oberon 1', 'Акустика', 'standard'),
  ('Dali', 'Oberon 3', 'Акустика', 'standard'),
  ('Dali', 'Rubicon 6', 'Акустика', 'standard'),
  ('ELAC', 'Debut 2.0 B6.2', 'Акустика', 'standard'),
  ('ELAC', 'Uni-Fi 2.0 UB5', 'Акустика', 'standard'),
  ('Wharfedale', 'Diamond 12.1', 'Акустика', 'standard'),
  ('Wharfedale', 'Linton', 'Акустика', 'standard'),
  ('Focal', 'Chora 806', 'Акустика', 'standard'),
  ('Focal', 'Aria 906', 'Акустика', 'standard'),
  ('Klipsch', 'RP-600M II', 'Акустика', 'standard'),
  ('Q Acoustics', '3020i', 'Акустика', 'standard'),
  ('Monitor Audio', 'Bronze 100', 'Акустика', 'standard'),
  ('Bowers & Wilkins', '607 S3', 'Акустика', 'standard'),
  ('Sonus Faber', 'Lumina II', 'Акустика', 'standard'),
  ('Tannoy', 'Revolution XT 6', 'Акустика', 'standard'),
  ('Audio-Technica', 'AT-LP7', 'Програвач', 'standard'),
  ('Audio-Technica', 'AT-LP120XUSB', 'Програвач', 'standard'),
  ('Rega', 'Planar 2', 'Програвач', 'standard'),
  ('Rega', 'Planar 3', 'Програвач', 'standard'),
  ('Pro-Ject', 'Debut Carbon Evo', 'Програвач', 'standard'),
  ('Pro-Ject', 'X1', 'Програвач', 'standard'),
  ('Technics', 'SL-1200GR', 'Програвач', 'standard'),
  ('Technics', 'SL-1500C', 'Програвач', 'standard'),
  ('Music Hall', 'MMF-2.3', 'Програвач', 'standard'),
  ('Clearaudio', 'Concept', 'Програвач', 'standard'),
  ('Thorens', 'TD 402 DD', 'Програвач', 'standard'),
  ('U-Turn', 'Orbit Plus', 'Програвач', 'standard'),
  ('Denon', 'DP-400', 'Програвач', 'standard'),
  ('Fluance', 'RT85', 'Програвач', 'standard'),
  ('VPI', 'Prime', 'Програвач', 'standard'),
  ('WiiM', 'Ultra', 'Стример', 'standard'),
  ('WiiM', 'Pro Plus', 'Стример', 'standard'),
  ('WiiM', 'Mini', 'Стример', 'standard'),
  ('Cambridge Audio', 'CXN V2', 'Стример', 'standard'),
  ('Bluesound', 'Node (2021)', 'Стример', 'standard'),
  ('Bluesound', 'Powernode', 'Стример', 'standard'),
  ('Sonos', 'Port', 'Стример', 'standard'),
  ('NAD', 'C 700', 'Стример', 'standard'),
  ('Naim', 'Uniti Atom', 'Стример', 'standard'),
  ('Yamaha', 'WXC-50', 'Стример', 'standard'),
  ('Eversolo', 'DMP-A6', 'Стример', 'standard'),
  ('Auralic', 'Aries Mini', 'Стример', 'standard'),
  ('Chord', 'Mojo 2', 'ЦАП', 'standard'),
  ('Chord', 'Qutest', 'ЦАП', 'standard'),
  ('RME', 'ADI-2 DAC FS', 'ЦАП', 'standard'),
  ('Topping', 'D90SE', 'ЦАП', 'standard'),
  ('SMSL', 'SU-9', 'ЦАП', 'standard'),
  ('Schiit', 'Modi 3+', 'ЦАП', 'standard'),
  ('iFi', 'ZEN DAC V2', 'ЦАП', 'standard'),
  ('Denafrips', 'Ares II', 'ЦАП', 'standard'),
  ('Cambridge Audio', 'DacMagic 200M', 'ЦАП', 'standard'),
  ('FiiO', 'K7', 'ЦАП', 'standard'),
  ('Pro-Ject', 'Phono Box S2', 'Фонокоректор', 'standard'),
  ('Rega', 'Fono Mini A2D', 'Фонокоректор', 'standard'),
  ('Cambridge Audio', 'Alva Duo', 'Фонокоректор', 'standard'),
  ('Musical Fidelity', 'V90-LPS', 'Фонокоректор', 'standard'),
  ('Schiit', 'Mani 2', 'Фонокоректор', 'standard'),
  ('NAD', 'PP 4', 'Фонокоректор', 'standard'),
  ('Graham Slee', 'Reflex M', 'Фонокоректор', 'standard'),
  ('Vincent', 'PHO-701', 'Фонокоректор', 'standard'),
  ('Sennheiser', 'HD 600', 'Навушники', 'standard'),
  ('Sennheiser', 'HD 660S2', 'Навушники', 'standard'),
  ('Sennheiser', 'Momentum 4', 'Навушники', 'standard'),
  ('Audio-Technica', 'ATH-M50x', 'Навушники', 'standard'),
  ('Audio-Technica', 'ATH-R70x', 'Навушники', 'standard'),
  ('Beyerdynamic', 'DT 990 Pro', 'Навушники', 'standard'),
  ('Beyerdynamic', 'DT 1990 Pro', 'Навушники', 'standard'),
  ('HiFiMAN', 'Sundara', 'Навушники', 'standard'),
  ('HiFiMAN', 'Edition XS', 'Навушники', 'standard'),
  ('Audeze', 'LCD-2', 'Навушники', 'standard'),
  ('Grado', 'SR325x', 'Навушники', 'standard'),
  ('Focal', 'Clear MG', 'Навушники', 'standard'),
  ('AKG', 'K702', 'Навушники', 'standard'),
  ('Sony', 'MDR-7506', 'Навушники', 'standard'),
  ('Sony', 'WH-1000XM5', 'Навушники', 'standard'),
  ('Meze', '99 Classics', 'Навушники', 'standard'),
  ('Schiit', 'Magni Heresy', 'Підсилювач для навушників', 'standard'),
  ('JDS Labs', 'Atom Amp 2', 'Підсилювач для навушників', 'standard'),
  ('FiiO', 'K11', 'Підсилювач для навушників', 'standard'),
  ('iFi', 'Zen Can', 'Підсилювач для навушників', 'standard'),
  ('Drop', 'THX AAA 789', 'Підсилювач для навушників', 'standard'),
  ('Woo Audio', 'WA7', 'Підсилювач для навушників', 'standard'),
  ('Little Dot', 'MK III', 'Підсилювач для навушників', 'standard'),
  ('Monoprice', 'Monolith Liquid Spark', 'Підсилювач для навушників', 'standard'),
  ('AudioQuest', 'NRG-X3', 'Кабелі', 'standard'),
  ('AudioQuest', 'Rocket 33', 'Кабелі', 'standard'),
  ('Tellurium Q', 'Black II', 'Кабелі', 'standard'),
  ('Chord Company', 'Clearway', 'Кабелі', 'standard'),
  ('QED', 'Reference XT40', 'Кабелі', 'standard'),
  ('Van den Hul', 'The Name', 'Кабелі', 'standard'),
  ('Kimber Kable', '8TC', 'Кабелі', 'standard'),
  ('Nordost', 'Blue Heaven', 'Кабелі', 'standard'),
  ('WireWorld', 'Eclipse 8', 'Кабелі', 'standard'),
  ('IsoAcoustics', 'Gaia I', 'Аксесуар', 'standard'),
  ('IsoAcoustics', 'ISO-155', 'Аксесуар', 'standard'),
  ('Auralex', 'GRAMMA', 'Аксесуар', 'standard'),
  ('Vicoustic', 'Wave Wood', 'Аксесуар', 'standard'),
  ('Sonos', 'Sub', 'Аксесуар', 'standard'),
  ('SVS', 'SB-1000 Pro', 'Аксесуар', 'standard'),
  ('AudioQuest', 'JitterBug', 'Аксесуар', 'standard'),
  ('Furutech', 'e-TP60', 'Аксесуар', 'standard')
on conflict (brand, model) do nothing;
