-- Broadens the catalogue beyond core electronics: racks, isolation, room
-- treatment, cartridges, subs, monitors, cables, tape/cassette, DSP.
insert into public.components (brand, model, category, origin) values
  ('Solidsteel', 'S3-4', 'Стійка', 'standard'),
  ('Solidsteel', 'HY-Base', 'Стійка', 'standard'),
  ('Atacama', 'Evoque Eco 60-40', 'Стійка', 'standard'),
  ('Atacama', 'Apollo Storm 6', 'Стійка', 'standard'),
  ('Quadraspire', 'SVT Bamboo', 'Стійка', 'standard'),
  ('Quadraspire', 'Q4 EVO', 'Стійка', 'standard'),
  ('Norstone', 'Stabbl', 'Стійка', 'standard'),
  ('Blok', 'Stax 2G', 'Стійка', 'standard'),
  ('Custom Design', 'Concept 400', 'Стійка', 'standard'),
  ('Target Audio', 'HR60', 'Стійка', 'standard'),
  ('Atacama', 'HMS 1.1', 'Підставка під акустику', 'standard'),
  ('Atacama', 'Nexus 6', 'Підставка під акустику', 'standard'),
  ('Solidsteel', 'SS-6', 'Підставка під акустику', 'standard'),
  ('Q Acoustics', 'Concept 20 Stands', 'Підставка під акустику', 'standard'),
  ('KEF', 'S2 Floor Stand', 'Підставка під акустику', 'standard'),
  ('Dali', 'Connect Stand E-600', 'Підставка під акустику', 'standard'),
  ('Monitor Audio', 'ASTAND', 'Підставка під акустику', 'standard'),
  ('Wharfedale', 'Denton Stand', 'Підставка під акустику', 'standard'),
  ('SVS', 'SB-2000 Pro', 'Сабвуфер', 'standard'),
  ('SVS', 'PB-1000 Pro', 'Сабвуфер', 'standard'),
  ('REL', 'T/5x', 'Сабвуфер', 'standard'),
  ('REL', 'T/7x', 'Сабвуфер', 'standard'),
  ('REL', 'S/510', 'Сабвуфер', 'standard'),
  ('KEF', 'KC62', 'Сабвуфер', 'standard'),
  ('BK Electronics', 'XLS200', 'Сабвуфер', 'standard'),
  ('Monitor Audio', 'Anthra W12', 'Сабвуфер', 'standard'),
  ('Velodyne', 'MicroVee X', 'Сабвуфер', 'standard'),
  ('Denon', 'AVR-X2800H', 'Ресивер', 'standard'),
  ('Denon', 'AVR-X3800H', 'Ресивер', 'standard'),
  ('Marantz', 'Cinema 70s', 'Ресивер', 'standard'),
  ('Yamaha', 'RX-A4A', 'Ресивер', 'standard'),
  ('Onkyo', 'TX-NR6100', 'Ресивер', 'standard'),
  ('Sony', 'STR-AN1000', 'Ресивер', 'standard'),
  ('Arcam', 'AVR11', 'Ресивер', 'standard'),
  ('Marantz', 'CD6007', 'CD-програвач', 'standard'),
  ('Marantz', 'SACD 30n', 'CD-програвач', 'standard'),
  ('Cambridge Audio', 'AXC35', 'CD-програвач', 'standard'),
  ('Denon', 'DCD-600NE', 'CD-програвач', 'standard'),
  ('Rotel', 'CD11 Tribute', 'CD-програвач', 'standard'),
  ('Audiolab', '6000CDT', 'CD-програвач', 'standard'),
  ('Yamaha', 'CD-S303', 'CD-програвач', 'standard'),
  ('Rega', 'Apollo', 'CD-програвач', 'standard'),
  ('Ortofon', '2M Red', 'Картридж', 'standard'),
  ('Ortofon', '2M Blue', 'Картридж', 'standard'),
  ('Ortofon', '2M Bronze', 'Картридж', 'standard'),
  ('Audio-Technica', 'AT-VM95ML', 'Картридж', 'standard'),
  ('Audio-Technica', 'AT-OC9XML', 'Картридж', 'standard'),
  ('Nagaoka', 'MP-110', 'Картридж', 'standard'),
  ('Nagaoka', 'MP-200', 'Картридж', 'standard'),
  ('Sumiko', 'Rainier', 'Картридж', 'standard'),
  ('Denon', 'DL-103', 'Картридж', 'standard'),
  ('Goldring', 'E3', 'Картридж', 'standard'),
  ('Grado', 'Prestige Gold3', 'Картридж', 'standard'),
  ('Hana', 'SL', 'Картридж', 'standard'),
  ('Pro-Ject', 'Vinyl Cleaner VC-E', 'Догляд за вінілом', 'standard'),
  ('Okki Nokki', 'Record Cleaning Machine', 'Догляд за вінілом', 'standard'),
  ('Knosti', 'Disco-Antistat', 'Догляд за вінілом', 'standard'),
  ('AudioQuest', 'Anti-Static Record Brush', 'Догляд за вінілом', 'standard'),
  ('Pro-Ject', 'Brush It', 'Догляд за вінілом', 'standard'),
  ('Analogue Studio', 'Stylus Cleaner', 'Догляд за вінілом', 'standard'),
  ('Spin-Clean', 'Record Washer MKII', 'Догляд за вінілом', 'standard'),
  ('Pro-Ject', 'Record Puck E', 'Догляд за вінілом', 'standard'),
  ('IsoTek', 'EVO3 Aquarius', 'Живлення', 'standard'),
  ('IsoTek', 'EVO3 Corvus', 'Живлення', 'standard'),
  ('Furman', 'PST-8', 'Живлення', 'standard'),
  ('Audioquest', 'PowerQuest 3', 'Живлення', 'standard'),
  ('Puritan Audio', 'PSM136', 'Живлення', 'standard'),
  ('Supra', 'MD06-EU MK3', 'Живлення', 'standard'),
  ('Tacima', 'CS929', 'Живлення', 'standard'),
  ('GigaWatt', 'PF-2 MK2', 'Живлення', 'standard'),
  ('GIK Acoustics', 'Bass Trap 244', 'Акустична обробка', 'standard'),
  ('GIK Acoustics', 'Alpha Panel', 'Акустична обробка', 'standard'),
  ('Vicoustic', 'Multifuser DC2', 'Акустична обробка', 'standard'),
  ('Vicoustic', 'Cinema Round Premium', 'Акустична обробка', 'standard'),
  ('Auralex', 'Studiofoam Wedges', 'Акустична обробка', 'standard'),
  ('Primacoustic', 'London 12', 'Акустична обробка', 'standard'),
  ('Artnovion', 'Andes Bass Trap', 'Акустична обробка', 'standard'),
  ('RPG', 'Skyline Diffusor', 'Акустична обробка', 'standard'),
  ('Sennheiser', 'IE 600', 'Внутрішньоканальні', 'standard'),
  ('Sennheiser', 'IE 200', 'Внутрішньоканальні', 'standard'),
  ('Moondrop', 'Aria 2', 'Внутрішньоканальні', 'standard'),
  ('Moondrop', 'Blessing 3', 'Внутрішньоканальні', 'standard'),
  ('7Hz', 'Salnotes Zero 2', 'Внутрішньоканальні', 'standard'),
  ('Truthear', 'Hexa', 'Внутрішньоканальні', 'standard'),
  ('Etymotic', 'ER2XR', 'Внутрішньоканальні', 'standard'),
  ('Campfire Audio', 'Andromeda', 'Внутрішньоканальні', 'standard'),
  ('Shure', 'SE215', 'Внутрішньоканальні', 'standard'),
  ('KZ', 'ZS10 Pro X', 'Внутрішньоканальні', 'standard'),
  ('Genelec', '8030C', 'Студійні монітори', 'standard'),
  ('Genelec', '8040B', 'Студійні монітори', 'standard'),
  ('Yamaha', 'HS8', 'Студійні монітори', 'standard'),
  ('KRK', 'Rokit 7 G4', 'Студійні монітори', 'standard'),
  ('Adam Audio', 'T7V', 'Студійні монітори', 'standard'),
  ('Adam Audio', 'A7V', 'Студійні монітори', 'standard'),
  ('Neumann', 'KH 120 II', 'Студійні монітори', 'standard'),
  ('Focal', 'Alpha 65 Evo', 'Студійні монітори', 'standard'),
  ('PreSonus', 'Eris E5', 'Студійні монітори', 'standard'),
  ('IK Multimedia', 'iLoud Micro', 'Студійні монітори', 'standard'),
  ('Bluesound', 'Pulse Mini 2i', 'Бездротова акустика', 'standard'),
  ('Sonos', 'Era 300', 'Бездротова акустика', 'standard'),
  ('Sonos', 'Five', 'Бездротова акустика', 'standard'),
  ('KEF', 'LSX II', 'Бездротова акустика', 'standard'),
  ('KEF', 'LS50 Wireless II', 'Бездротова акустика', 'standard'),
  ('Dali', 'Oberon 7 C', 'Бездротова акустика', 'standard'),
  ('Naim', 'Mu-so 2', 'Бездротова акустика', 'standard'),
  ('Audio Pro', 'A26', 'Бездротова акустика', 'standard'),
  ('Ruark', 'R3', 'Бездротова акустика', 'standard'),
  ('Triangle', 'AIO 3', 'Бездротова акустика', 'standard'),
  ('Rotel', 'RB-1590', 'Підсилювач потужності', 'standard'),
  ('Emotiva', 'BasX A2', 'Підсилювач потужності', 'standard'),
  ('Hypex', 'NCore NC252MP', 'Підсилювач потужності', 'standard'),
  ('Parasound', 'A23+', 'Підсилювач потужності', 'standard'),
  ('Audiolab', '8300XP', 'Підсилювач потужності', 'standard'),
  ('NAD', 'C 268', 'Підсилювач потужності', 'standard'),
  ('Bryston', '3B Cubed', 'Підсилювач потужності', 'standard'),
  ('Fosi Audio', 'V3', 'Підсилювач потужності', 'standard'),
  ('Schiit', 'Freya+', 'Попередній підсилювач', 'standard'),
  ('Rotel', 'RC-1572 MKII', 'Попередній підсилювач', 'standard'),
  ('Audiolab', '8300A Pre', 'Попередній підсилювач', 'standard'),
  ('Parasound', 'P6', 'Попередній підсилювач', 'standard'),
  ('NAD', 'C 658', 'Попередній підсилювач', 'standard'),
  ('Cambridge Audio', 'Azur 851E', 'Попередній підсилювач', 'standard'),
  ('Primare', 'PRE35', 'Попередній підсилювач', 'standard'),
  ('Van den Hul', 'The Wind', 'Кабелі', 'standard'),
  ('Supra', 'Ply 3.4/S', 'Кабелі', 'standard'),
  ('Chord Company', 'C-Screen', 'Кабелі', 'standard'),
  ('Chord Company', 'Epic X', 'Кабелі', 'standard'),
  ('QED', 'Silver Anniversary XT', 'Кабелі', 'standard'),
  ('AudioQuest', 'Golden Gate', 'Кабелі', 'standard'),
  ('AudioQuest', 'Carbon USB', 'Кабелі', 'standard'),
  ('Atlas', 'Hyper 3.5', 'Кабелі', 'standard'),
  ('Mogami', 'W2549', 'Кабелі', 'standard'),
  ('Canare', '4S11', 'Кабелі', 'standard'),
  ('Blue Jeans Cable', 'Belden 5000UE', 'Кабелі', 'standard'),
  ('Nordost', 'Purple Flare', 'Кабелі', 'standard'),
  ('Teac', 'A-6300', 'Котушковий магнітофон', 'standard'),
  ('Revox', 'B77 MKII', 'Котушковий магнітофон', 'standard'),
  ('Akai', 'GX-635D', 'Котушковий магнітофон', 'standard'),
  ('Tascam', '32', 'Котушковий магнітофон', 'standard'),
  ('Nakamichi', 'Dragon', 'Касетна дека', 'standard'),
  ('Nakamichi', 'CR-7A', 'Касетна дека', 'standard'),
  ('Teac', 'W-1200', 'Касетна дека', 'standard'),
  ('Sony', 'TC-K870ES', 'Касетна дека', 'standard'),
  ('Pioneer', 'CT-S920S', 'Касетна дека', 'standard'),
  ('Magnum Dynalab', 'MD 90T', 'Тюнер', 'standard'),
  ('Sansui', 'TU-717', 'Тюнер', 'standard'),
  ('Onkyo', 'T-4711', 'Тюнер', 'standard'),
  ('Denon', 'TU-1500AE', 'Тюнер', 'standard'),
  ('Roon', 'Nucleus One', 'Медіа-сервер', 'standard'),
  ('Innuos', 'ZENmini Mk3', 'Медіа-сервер', 'standard'),
  ('Melco', 'N100', 'Медіа-сервер', 'standard'),
  ('Synology', 'DS224+', 'Медіа-сервер', 'standard'),
  ('Raspberry Pi', '4 + Volumio', 'Медіа-сервер', 'standard'),
  ('miniDSP', 'Flex', 'Процесор / DSP', 'standard'),
  ('miniDSP', '2x4 HD', 'Процесор / DSP', 'standard'),
  ('Dirac', 'Live Processor', 'Процесор / DSP', 'standard'),
  ('Anthem', 'STR', 'Процесор / DSP', 'standard'),
  ('Lyngdorf', 'RoomPerfect', 'Процесор / DSP', 'standard'),
  ('Behringer', 'DEQ2496', 'Процесор / DSP', 'standard'),
  ('Schiit', 'Loki Max', 'Еквалайзер', 'standard'),
  ('Schiit', 'Lokius', 'Еквалайзер', 'standard'),
  ('SPL', 'Passeq', 'Еквалайзер', 'standard'),
  ('Technics', 'SH-8065', 'Еквалайзер', 'standard'),
  ('IsoAcoustics', 'Orea Bordeaux', 'Віброізоляція', 'standard'),
  ('IsoAcoustics', 'Aperta 200', 'Віброізоляція', 'standard'),
  ('Townshend Audio', 'Seismic Pods', 'Віброізоляція', 'standard'),
  ('Symposium', 'Rollerblock Jr', 'Віброізоляція', 'standard'),
  ('Solid Tech', 'Disc of Silence', 'Віброізоляція', 'standard'),
  ('SVS', 'SoundPath Isolation Feet', 'Віброізоляція', 'standard'),
  ('Auralex', 'SubDude-II', 'Віброізоляція', 'standard'),
  ('Kanto', 'SX22', 'Віброізоляція', 'standard')
on conflict (brand, model) do nothing;
